POST http://localhost:3333/pratos
Content-Type: application/json

{
    "name": "barca de camarao",
    "foto": "foto_barca.png",
    "description": "esta barca contem camarao",
    "price": 199
}

###

GET http://localhost:3333/pratos

###

PUT http://localhost:3333/pratos
Content-Type: application/json

{
    "name": "temaki",
    "foto": "foto_temaki.png",
    "description": "temaki",
    "price": 25
}

###

DELETE http://localhost:3333/pratos

###


### Cliente

POST http://localhost:3333/cliente
Content-Type: application/json

{
    "nome": "João Souza Silvas",
    "gmail": "testesis@gmail.com",
    "whats": "48999601266"
}

###

GET http://localhost:3333/cliente

###

PUT http://localhost:3333/cliente/
Content-Type: application/json

{
    "nome": "Leonardo",
    "gmail": "leonardokorb@gmail.com",
    "whats": "99958-1235"
}

###

DELETE http://localhost:3333/cliente/
###


### Pedido

POST http://localhost:3333/pedido
Content-Type: application/json

    {
        "quant": 1,
        "status": "n",
        "datapedid": "2024-09-12T12:12:00",
        "valor_total": 50.0,
        "desc_pedido": "Pedido de sushi"
    }

###

GET http://localhost:3333/pedido

###

PUT http://localhost:3333/pedido
Content-Type: application/json

{
    "quant": 2,
    "status": "f",
    "datapedid": "2024-09-12T12:31:00",
    "valor_total": 100.0,
    "desc_pedido": "Pedido de sushi para dois",
}

###

DELETE http://localhost:3333/pedido

###


### Restaurante

POST http://localhost:3333/restaurante
Content-Type: application/json

{
    "cnpj": "12345678901229",
    "nome": "Restaurante v",
    "endereco": "Rua Exemplo, 323",
    "cep": "1234564",
    "cidade": "São Joaquim do sul",
    "bairro": "Interior de sp",
    "num": 12,
    "compl": "ao lado da padaria da rosa",
    "telefone": "21999999449",
    "capacidade": 40
}

###

GET http://localhost:3333/restaurante

###

PUT http://localhost:3333/restaurante
Content-Type: application/json

{
    "cnpj": "12345678901234",
    "nome": "Restaurante A",
    "endereco": "Rua Exemplo, 123",
    "cep": "12345000",
    "cidade": "São Paulo",
    "bairro": "Centro",
    "num": "123",
    "compl": "fim da rua",
    "telefone": "11999999999",
    "capacidade": "100"
}

###

DELETE http://localhost:3333/restaurante

