POST http://localhost:3333/pratos
Content-Type: application/json

{
    "name": "Bebida de limão",
    "foto": "https://i.pinimg.com/736x/d9/35/2f/d9352f8cf0023ef14f1f73e70f668ebe.jpg",
    "description": "Bebida gelada",
    "price": 22.50,
    "tipoprato": "E"
}

###

GET http://localhost:3333/pratos

###

PUT http://localhost:3333/pratos/
Content-Type: application/json

{
    "name": "temaki",
    "foto": "foto_temaki.png",
    "description": "temaki",
    "price": 25,
    "tipoprato": "P"
    
}

###

DELETE http://localhost:3333/pratos/

###


### Cliente

POST http://localhost:3333/cliente
Content-Type: application/json

{
    "nome": "João Souza Silvasis",
    "gmail": "joao@gmail.com",
    "whats": "48999601234"
}



###

GET http://localhost:3333/cliente

###

PUT http://localhost:3333/cliente/
Content-Type: application/json

{
    "nome": "Leonardo",
    "gmail": "leonardokorb@gmail.com",
    "whats": "99958-1235"
}

###

DELETE http://localhost:3333/cliente/
###


### Pedido

POST http://localhost:3333/pedido
Content-Type: application/json

    {
    "quant": 1,
    "status": "n",
    "datapedid": "2024-09-12T12:12:00",
    "valor_total": 50.0,
    "desc_pedido": "Pedido de sushi",
    "pratosid": "1c2c5397-9c09-45bf-b4b9-81d5dd1e71ba",         
    "id_comanda_num": "95fa714c-7b26-4b67-a1cd-041b7eedc204",  
    "idRestaurante": "7270890b-fbc8-4b7f-ad74-b4c10b94fef4"
}

###

GET http://localhost:3333/pedido

###

PUT http://localhost:3333/pedido
Content-Type: application/json

{
    "quant": 2,
    "status": "f",
    "datapedid": "2024-09-12T12:31:00",
    "valor_total": 100.0,
    "desc_pedido": "Pedido de sushi para dois",
}

###

DELETE http://localhost:3333/pedido/

###


### Restaurante

POST http://localhost:3333/restaurante
Content-Type: application/json

{
    "cnpj": "12345678901229",
    "nome": "Restaurante v",
    "endereco": "Rua Exemplo, 323",
    "cep": "1234564",
    "cidade": "São Joaquim do sul",
    "bairro": "Interior de sp",
    "num": 12,
    "compl": "ao lado da padaria da rosa",
    "telefone": "21999999449",
    "capacidade": 40
}

###

GET http://localhost:3333/restaurante

###

PUT http://localhost:3333/restaurante
Content-Type: application/json

{
    "cnpj": "12345678901234",
    "nome": "Restaurante A",
    "endereco": "Rua Exemplo, 123",
    "cep": "12345000",
    "cidade": "São Paulo",
    "bairro": "Centro",
    "num": "123",
    "compl": "fim da rua",
    "telefone": "11999999999",
    "capacidade": "100"
}

###

DELETE http://localhost:3333/restaurante/75abb852-340f-4138-b05e-8a239679b525

###
 
POST http://localhost:3333/comanda
Content-Type: application/json

   {
    "usuarioid": "3620ba71-57e2-477a-b143-84ce1eca883b",
    "pratosid": "1c2c5397-9c09-45bf-b4b9-81d5dd1e71ba",
    "idRestaurante": "7270890b-fbc8-4b7f-ad74-b4c10b94fef4"
   }

